version: "3.9"

services:
  backend-core:
    build: ../backend-core
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: "super-secret-key"
      DATABASE_URL: "sqlite:///./core.db"
    volumes:
      - core_data:/app/data

  backend-queue:
    build: .
    ports:
      - "8001:8001"
    environment:
      SECRET_KEY: "super-secret-key"                
      DATABASE_URL: "sqlite:///./queue.db"
      CORE_API_URL: "http://backend-core:8000"
    depends_on:
      - backend-core
    volumes:
      - queue_data:/app/data

volumes:
  core_data:
  queue_data: