"""initial tables setup

Revision ID: 432b0b64aa01
Revises: 
Create Date: 2026-09-18 16:33:12.794430

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '432b0b64aa01'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
