"""add ticket priority and window number

Revision ID: f4125985336c
Revises: 432b0b64aa01
Create Date: 2026-09-19 11:32:21.365875

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f4125985336c'
down_revision: Union[str, None] = '432b0b64aa01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.add_column('tickets', sa.Column('priority', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_tickets_priority'), 'tickets', ['priority'], unique=False)
    op.alter_column('tickets', 'priority', server_default=None)

    op.add_column('windows', sa.Column('number', sa.Integer(), nullable=True))
    op.execute("UPDATE windows SET number = id WHERE number IS NULL")
    op.alter_column('windows', 'number', nullable=False)
    op.create_index(op.f('ix_windows_number'), 'windows', ['number'], unique=True)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_windows_number'), table_name='windows')
    op.drop_column('windows', 'number')
    op.drop_index(op.f('ix_tickets_priority'), table_name='tickets')
    op.drop_column('tickets', 'priority')
    # ### end Alembic commands ###
