"""initial tickets

Revision ID: 1b5b7ac23e56
Revises: 
Create Date: 2026-09-19 03:29:35.690345
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1b5b7ac23e56'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=10), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('queue_date', sa.Date(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=120), nullable=False),
    sa.Column('service_prefix', sa.String(length=2), nullable=False),
    sa.Column('avg_minutes', sa.Integer(), nullable=True),
    sa.Column('window_id', sa.Integer(), nullable=True),
    sa.Column('window_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('waiting', 'called', 'in_progress', 'completed', 'cancelled', 'no_show', name='ticketstatus'), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('called_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback_comment', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_number'), 'tickets', ['number'], unique=False)
    op.create_index(op.f('ix_tickets_queue_date'), 'tickets', ['queue_date'], unique=False)
    op.create_index(op.f('ix_tickets_service_id'), 'tickets', ['service_id'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_window_id'), 'tickets', ['window_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_window_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_service_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_queue_date'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_number'), table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###